### ISSUE TITLE
Install not seeming to work.

### ISSUE THREAD

**Issue by rtruong2** [mnick/scikit-tensor#34]
when I run "pip install scikit-tensor", I get:

Collecting scikit-tensor
  Using cached scikit-tensor-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n2fgdtqa/scikit-tensor/setup.py", line 79
        print mod.__version__
                ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n2fgdtqa/scikit-tensor/

What could the issue with this be coming from?

**Comment by wohlert** [comment]
You run into this error because you are running Python 3+. The package is not yet implemented for this version of Python and it does not seem like the creator is maintaining the project anymore.

If you install Python 2 and install this package you should have no problems.

**Comment by agjayant** [comment]
Installing in development mode seems to work for Python 3.6. Is it fixed entirely for Python 3+, or there are some issues ?

**Comment by KKaltdorf** [comment]
Hi, I have the same problem (see error message below). The installation doesn't work although I have python 2 installed. Installation in development mode didn't work too. Can you help me?

wbbi106:/home/krs66uc/anaconda3/SuRVoS # ./SuRVoS 
Traceback (most recent call last):
  File "./SuRVoS", line 7, in <module>
    import h5py as h5
ImportError: No module named h5py
wbbi106:/home/krs66uc/anaconda3/SuRVoS # exit
exit
wbbi106:~/anaconda3/SuRVoS> su
Passwort: 
wbbi106:/home/krs66uc/anaconda3/SuRVoS # pip install --upgrade scikit-tensor
Collecting scikit-tensor
  Using cached scikit-tensor-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kwwjrqn0/scikit-tensor/setup.py", line 79
        print mod.__version__
                ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kwwjrqn0/scikit-tensor/
wbbi106:~/Programme/SuRVoS> python --version
Python 2.7.13

**Comment by wohlert** [comment]
When you are running `pip install --upgrade scikit-tensor` it looks like it defaults to Python 3. You could perhaps try `pip2 install --upgrade scikit-tensor`?

**Comment by evertrol** [comment]
Installing directly from the repository appears to work:

```
python3 -m pip install git+https://github.com/mnick/scikit-tensor.git
```

though some unit tests fail for (yet) unknown reasons.

**Comment by lavaait** [comment]
> Installing directly from the repository appears to work:
> 
> ```
> python3 -m pip install git+https://github.com/mnick/scikit-tensor.git
> ```
> 
> though some unit tests fail for (yet) unknown reasons.

Yes this works for me.Thank you
