### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by MaxLingwei** [mnick/scikit-tensor#36]
Hello, i tried to use 
` pip2 install scikit-tensor`
to install but failed. The error imformation
> Collecting scikit-tensor
  Using cached scikit-tensor-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    setuptools module not found.
    Install setuptools if you want to enable 'python setup.py develop'.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6yTuyk/scikit-tensor/setup.py", line 53, in <module>
        require('numpy', 'scipy', 'nose')
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'nose' distribution was not found and is required by the application

How to install successfully? Thank you!

**Comment by seralouk** [comment]
use first: `pip install nose` and then `pip install scikit-tensor`
