### ISSUE TITLE
Installation error: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(mod.__version__)?

### ISSUE THREAD

**Issue by BhuvaneshBhatt** [mnick/scikit-tensor#38]
I'm getting a fatal installation error when installing scikit-tensor on my Mac:

~$ pip3 --version
pip 10.0.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip (python 3.6)
~$ pip3 install scikit-tensor
Collecting scikit-tensor
  Using cached https://files.pythonhosted.org/packages/e9/5e/2ce76cc8f9da0517085e17cd70210ed996aeb8f972e7080d0bc89d82bbd9/scikit-tensor-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4y/cwpdv5dd37q0djhsgnr558m0000b4c/T/pip-install-4m41b2gw/scikit-tensor/setup.py", line 79
        print mod.__version__
                ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(mod.__version__)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4y/cwpdv5dd37q0djhsgnr558m0000b4c/T/pip-install-4m41b2gw/scikit-tensor/
~$

**Comment by evertrol** [comment]
Dupe of #34 . See that issue for a possible solution to installing this package.
